stages:
  - build

variables:
  DOCKER_IMAGE_NAME: "index.docker.io/bbertka/stock-flask-app:latest"
  DOCKER_FILE: "Dockerfile"
  DOCKER_REGISTRY: "docker.io"

build-docker-image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_USERNAME" -p "DOCKER_PASSWORD" $DOCKER_REGISTRY
  script:
    - docker build -t $DOCKER_IMAGE_NAME -f $DOCKER_FILE .
    - docker push $DOCKER_IMAGE_NAME
  only:
    - main
