stages:
  - build

variables:
  DOCKER_IMAGE_NAME: "bbertka/stock-flask-app:latest"
  DOCKER_FILE: "Dockerfile"

build-docker-image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin # Login to Docker Hub
  script:
    - docker build -t $DOCKER_IMAGE_NAME -f $DOCKER_FILE .
    - docker push $DOCKER_IMAGE_NAME
  only:
    - main
