stages:
  - deploy

variables:
  DOCKER_FILE: "Dockerfile"
  DOCKER_REGISTRY: "docker.io"
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_IMAGE_NAME: "bbertka/stock-flask-app"  # Base image name
  DOCKER_BASE_TAG: "latest"  # Base tag

deploy-k3s:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - echo "$SSL_CERT_FILE" > kas_ca.crt
    - kubectl config use-context bbertka/stock-flask-app:k3s
    - kubectl apply -f deployment.yml -n $KUBE_NAMESPACE --certificate-authority=kas_ca.crt
    - DEPLOYMENT_NAME=$(grep 'name:' deployment.yml | awk 'NR==1{print $2}')
    - kubectl rollout restart deployment/$DEPLOYMENT_NAME -n $KUBE_NAMESPACE --certificate-authority=kas_ca.crt
  only:
    - main

