# role.yml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev01
  name: gitlab-deployer-role
rules:
- apiGroups: ["", "apps", "extensions"]
  resources: ["deployments", "replicasets", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
